language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - build-tools-28.0.3
    - platform-tools

before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

before_install:
  - yes | sdkmanager "platforms;android-28"

notifications:
    email:
        - alessandro.crugnola@gmail.com

cache: false
sudo: false

install:
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
  - ./gradlew clean build lint assemble

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
